# Arithmetic Operation in numpy

In [1]:
import numpy as np
var=np.array([1,2,3,4])
varAdd=var+3
print(varAdd)

[4 5 6 7]


In [2]:
var=np.array([1,2,3,4])
var1=np.array([3,4,5,6])
varAdd=var+var1
print(varAdd)

[ 4  6  8 10]


In [3]:
import numpy as np
var=np.array([1,2,3,4])
varAdd=var-3
print(varAdd)

[-2 -1  0  1]


In [4]:
import numpy as np
var=np.array([1,2,3,4])
varAdd=var*3
print(varAdd)

[ 3  6  9 12]


In [1]:
import numpy as np
var=np.array([1,2,3,4])
varAdd=var/3
print(varAdd)

[0.33333333 0.66666667 1.         1.33333333]


In [6]:
import numpy as np
var=np.array([1,2,3,4])
varAdd=var//3
print(varAdd)

[0 0 1 1]


In [7]:
import numpy as np
var=np.array([1,2,3,4])
varAdd=var%3
print(varAdd)

[1 2 0 1]


#using function for arithmetic operation

In [8]:
var=np.array([1,2,3,4])
var1=np.array([3,4,5,6])
varAdd=np.add(var,var1)
print(varAdd)

[ 4  6  8 10]


In [9]:
var=np.array([1,2,3,4])
var1=np.array([3,4,5,6])
varAdd=np.add(var,3)
print(varAdd)

[4 5 6 7]


2D Array

In [11]:
#2D Array
var=np.array([[1,2,3,4],[4,5,6,7]])
varAdd=var%3
print(varAdd)

[[1 2 0 1]
 [1 2 0 1]]


In [17]:
#Arithmetic operation
var=np.array([[1,2,3,4],[4,5,6,7]])
print(var)
print()
var1=np.array([[2,3,4,5],[6,7,8,9]])
print(var1)
print()

varAdd=var+var1
print(varAdd)

[[1 2 3 4]
 [4 5 6 7]]

[[2 3 4 5]
 [6 7 8 9]]

[[ 3  5  7  9]
 [10 12 14 16]]


In [3]:
var=np.array([1,2,1,4])
varAdd=np.reciprocal(var)
print(varAdd)

[1 0 1 0]


In [19]:
var=np.array([[1,2,3,4],[4,5,6,7]])
print(var)
print()
var1=np.array([[2,3,4,5],[6,7,8,9]])
print(var1)
print()

varAdd=np.multiply(var,var1)
print(varAdd)

[[1 2 3 4]
 [4 5 6 7]]

[[2 3 4 5]
 [6 7 8 9]]

[[ 2  6 12 20]
 [24 35 48 63]]
