# Arithmetic Function

In [3]:
#Shuffle
import numpy as np
var=np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 2 5 1 4]


In [4]:
#unique
var=np.array([1,2,3,4,2,5,3,6,2,7])
x=np.unique(var)
print(x)

[1 2 3 4 5 6 7]


In [8]:
#unique
var=np.array([1,2,3,4,2,5,3,6,2,7])

#printing index number and count
x=np.unique(var,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64), array([1, 3, 2, 1, 1, 1, 1], dtype=int64))


Resize

In [9]:
#Resize
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [10]:
#Resize
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
#flatten

var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y,"\n")

print(y.flatten())

[1 2 3 4 5 6]


In [21]:
#flatten

var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y,"\n")

#changing the order
print("Flatten :",y.flatten(order="C"),"\n") #row major
print("Flatten :",y.flatten(order="F"),"\n") #column major
print("Flatten :",y.flatten(order="A"),"\n")
print("Flatten :",y.flatten(order="K"),"\n")


print("Ravel :",y.ravel(order="C"),"\n")
print("Ravel :",y.ravel(order="F"),"\n")
print("Ravel :",y.ravel(order="A"),"\n")
print("Ravel :",y.ravel(order="K"),"\n")



[[1 2]
 [3 4]
 [5 6]] 

Flatten : [1 2 3 4 5 6] 

Flatten : [1 3 5 2 4 6] 

Flatten : [1 2 3 4 5 6] 

Flatten : [1 2 3 4 5 6] 

Ravel : [1 2 3 4 5 6] 

Ravel : [1 3 5 2 4 6] 

Ravel : [1 2 3 4 5 6] 

Ravel : [1 2 3 4 5 6] 

