# Data type in Numpy array

In [1]:
import numpy as np
var=np.array([1,2,3,4,5])
print("Data type :",var.dtype)

Data type : int32


In [2]:
var=np.array([1.3,2.5,3.2,4.1,5.3])
print("Data type :",var.dtype)

Data type : float64


In [3]:
var=np.array(["a","b","c","d","e"])
print("Data type :",var.dtype)

Data type : <U1


In [6]:
#if we are give the numbers or string in array .then hamara data type bhi change ho jata hai
var=np.array(["a","b","c",1,2,3])
print("Data type :",var.dtype)

var=np.array(["a","b","c",1,2,3.2])
print("Data type :",var.dtype)

Data type : <U11
Data type : <U32


In [9]:
#changing the data type
arr=[2,4,6,5]
x=np.array(arr,dtype=np.int8)
print("Data type :",x.dtype)
print(x)

Data type : int8
[2 4 6 5]


In [10]:
#Another way of changing data type
arr=[2,4,6,5]
x=np.array(arr,dtype="f")
print("Data type :",x.dtype)
print(x)

Data type : float32
[2. 4. 6. 5.]


In [14]:
#changing data type through function
x1=np.array([2,3,4])
print("Data type :",x1.dtype)
print(x1)

new=np.float32(x1)
print("Data type :",new.dtype)
print(new)

Data type : int32
[2 3 4]
Data type : float32
[2. 3. 4.]


In [15]:
#changing data type through function
x1=np.array([2,3,4])
print("Data type :",x1.dtype)
print(x1)

new=np.float32(x1)
print("Data type :",new.dtype)
print(new)

new1=np.int_(new)
print("Data type :",new1.dtype)
print(new1)

Data type : int32
[2 3 4]
Data type : float32
[2. 3. 4.]
Data type : int32
[2 3 4]


In [16]:
x3=np.array([2,3,4])
new2=x3.astype(float)
print(x3)
print(new2)

[2 3 4]
[2. 3. 4.]
