Indexing And Slicing in numpy Array

In [1]:
#indexing numpy Array
import numpy as np
var=np.array([3,4,8,5,4])
print(var[1])
print(var[-3])

4
8


In [6]:
var1=np.array([[7,8,9],[2,3,4]])
print(var1)
print(var1.ndim)
print()

# print(var1[1][2])
print(var1[1,2])

[[7 8 9]
 [2 3 4]]
2

4


In [8]:
var2=np.array([[[1,2],[1,2]]])
print(var2)
print(var2.ndim)
print()
print(var2[0,1,1])

[[[1 2]
  [1 2]]]
3

2


Slicing numpy array

In [16]:
#slicing in one dimension array
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
print(var,"\n")
print("2 to 5 :",x[1:5])
print("2 to end :",x[1:])
print("start to 5 :",x[:5])

[3 4 8 5 4] 

2 to 5 : [2 3 4 5]
2 to end : [2 3 4 5 6 7 8 9]
start to 5 : [1 2 3 4 5]


In [17]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
print(var,"\n")
print("2 to 5 :",x[1:5])
print("2 to end :",x[1:])
print("start to 5 :",x[:5])

print("Stop :",x[::2])
print("Stop :",x[1:5:2])
print("Stop :",x[1:6:2])

[3 4 8 5 4] 

2 to 5 : [2 3 4 5]
2 to end : [2 3 4 5 6 7 8 9]
start to 5 : [1 2 3 4 5]
Stop : [1 3 5 7 9]
Stop : [2 4]
Stop : [2 4 6]


In [18]:
#slicing in two dimension array
y1=np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1,"\n")
print("8 to 5 : ",y1[1,1:])
print("12 to 15 : ",y1[2,1:])


[[7 8 9]
 [2 3 4]] 

8 to 5 :  [8 7 6 5]
12 to 15 :  [12 13 14 15]
