# Join And Split Functions

In [6]:
import numpy as np
var2=np.array([[1,2],[3,4]])
var3=np.array([[5,6],[7,8]])

# ar=np.concatenate((var2,var3))
# ar=np.concatenate((var2,var3),axis=0)
ar=np.concatenate((var2,var3),axis=1)
print(ar)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
#Merging two array using stack function
import numpy as np
vr1=np.array([1,2,3,4])
vr2=np.array([5,6,7,8])

# ar=np.stack((vr1,vr2))
ar=np.stack((vr1,vr2),axis=1)
print(ar)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [12]:
#Merging two array using stack function
import numpy as np
vr1=np.array([1,2,3,4])
vr2=np.array([5,6,7,8])

ar=np.hstack((vr1,vr2)) #row
print(ar)

[1 2 3 4 5 6 7 8]


In [18]:
#Merging two array using stack function
import numpy as np
vr1=np.array([1,2,3,4])
vr2=np.array([5,6,7,8])

# ar=np.stack((vr1,vr2),axis=0)
ar=np.vstack((vr1,vr2)) #columns
print(ar)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
#Merging two array using stack function
import numpy as np
vr1=np.array([1,2,3,4])
vr2=np.array([5,6,7,8])

# ar=np.stack((vr1,vr2),axis=1)
ar=np.dstack((vr1,vr2)) #height
print(ar)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


# Split Array

In [26]:
import numpy as np
var=np.array([1,2,3,4,5,6])
print(var,"\n")
ar=np.array_split(var,3)
# ar=np.array_split(var,4)
# ar=np.array_split(var,2)
# ar=np.array_split(var,8)

print(ar)

#hum jab array ko split karate hai tab hame list type new data type milta hai.
print(type(ar))

print(ar[0])
print(ar[1])
print(ar[2])

[1 2 3 4 5 6] 

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]
[3 4]
[5 6]


In [29]:
import numpy as np
var4=np.array([[1,2],[3,4],[5,6]])
print(var,"\n")
ar1=np.array_split(var4,3)

print(ar1)

#hum jab array ko split karate hai tab hame list type new data type milta hai.
print(type(ar))



[[1 2]
 [3 4]
 [5 6]] 

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>


In [32]:
# Spliting array along the axis

import numpy as np
var4=np.array([[1,2],[3,4],[5,6]])
print(var,"\n")
ar1=np.array_split(var4,3)
ar2=np.array_split(var4,3,axis=1)

print(ar1,"\n\n")
print(ar2,"\n\n")

#hum jab array ko split karate hai tab hame list type new data type milta hai.
print(type(ar))



[[1 2]
 [3 4]
 [5 6]] 

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])] 


[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)] 


<class 'list'>
