# Matrix in Numpy Arrays

In [7]:
#array
import numpy as np
var=np.array([[1,2,3],[4,5,6]])
print(var)
print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [6]:
#matrix
import numpy as np
var1=np.matrix([[1,2,3],[4,5,6]])
print(var)
print(type(var1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


# Arithmetic operation in matrix

In [11]:
#matrix addition
import numpy as np
var1=np.matrix([[1,2,3],[4,5,6]])
var2=np.matrix([[2,3,4],[5,6,7]])

print(var1,"\n")
print(var2,"\n")

print("Addition :\n",var1+var2)


[[1 2 3]
 [4 5 6]] 

[[2 3 4]
 [5 6 7]] 

Addition :
 [[ 3  5  7]
 [ 9 11 13]]


In [13]:
#matrix multiplication
import numpy as np
var1=np.matrix([[1,2],[4,5]])
var2=np.matrix([[2,3],[5,6]])

print(var1,"\n")
print(var2,"\n")

print("multiplication :\n",var1*var2)
print("multiplication :\n",var1.dot(var2))

[[1 2]
 [4 5]] 

[[2 3]
 [5 6]] 

multiplication :
 [[12 15]
 [33 42]]
multiplication :
 [[12 15]
 [33 42]]


# Matrix Functions in Numpy Arrays

In [14]:
import numpy as np
var=np.matrix([[1,2,3],[4,5,6]])
print(var)


[[1 2 3]
 [4 5 6]]


In [21]:
# Transpose
import numpy as np
var=np.matrix([[1,2,3],[4,5,6]])
print(var)
print(np.transpose(var),"\n")
print(var.T,"\n")

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]] 

[[1 4]
 [2 5]
 [3 6]] 



In [24]:
# Swapaxes
import numpy as np
var=np.matrix([[1,2,3],[4,5,6]])
print(var)
print(np.swapaxes(var,0,1),"\n")
print(var.T,"\n")

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]] 

[[1 4]
 [2 5]
 [3 6]] 



In [1]:
# Swapaxes
import numpy as np
var=np.matrix([[1,2,3],[4,5,6]])
print(var)
print(np.swapaxes(var,1,0),"\n")

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]] 



In [29]:
# Swapaxes
import numpy as np
var1=np.matrix([[1,2],[4,5]])
print(var1)
print(np.swapaxes(var1,0,1),"\n")


[[1 2]
 [4 5]]
[[1 4]
 [2 5]] 



In [2]:
# Swapaxes
import numpy as np
var1=np.matrix([[1,2],[3,4]])
print(var1)
print(np.linalg.inv(var1),"\n")


[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]] 



In [11]:
#Power of metrix

#n=0 (Identity metrix)
#n>0 (Power(mult))
#n<0 (Inverse*power)

import numpy as np
var2=np.matrix([[1,2],[3,4]])
print(var2)
print(np.linalg.matrix_power(var2,2),"\n")
print(np.linalg.matrix_power(var2,0),"\n")
print(np.linalg.matrix_power(var2,-2),"\n")

[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]] 

[[1 0]
 [0 1]] 

[[ 5.5  -2.5 ]
 [-3.75  1.75]] 



In [8]:
# Determinant of matrix
import numpy as np
var3=np.matrix([[1,2,3],[2,3,4],[1,2,3]])
print(var3)
print(np.linalg.det(var3),"\n")

[[1 2 3]
 [2 3 4]
 [1 2 3]]
0.0 



In [10]:
# Determinant of matrix
import numpy as np
var3=np.matrix([[4,5,8],[2,3,4],[1,2,3]])
print(var3)
print(np.linalg.det(var3),"\n")

[[4 5 8]
 [2 3 4]
 [1 2 3]]
2.0000000000000004 

