In [2]:
#Atribute of numpy
import numpy as np
arr=np.array([3,4,5,6,7])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[3 4 5 6 7]
1
(5,)
5
int32
4


In [3]:
#Atribute of numpy
import numpy as np
arr=np.array([[3,4,5],[5,6,7]])
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[3 4 5]
 [5 6 7]]
2
(2, 3)
6
int32
4


In [5]:
#getting array element through index.
arr=np.array([3,4,7,5,6,7])
print(arr[0])
print(arr[-1])
print(arr[-3])
print(arr[-2])

3
7
5
6
