Operation on numpy array

In [3]:
#matrix transpose
import numpy as np
var1=np.array([3,4,5,7,8])
print("the transpose of the metrix :",var1.T)

the transpose of the metrix : [3 4 5 7 8]


In [4]:
import numpy as np
var1=np.array([[3,4,5],[1,2,3],[4,5,6]])
print("the transpose of the metrix :",var1.T)

the transpose of the metrix : [[3 1 4]
 [4 2 5]
 [5 3 6]]


In [7]:
#WAP To perform the matrix addition multiplication , subtraction , division etc.
import numpy as np
x=np.array([1,2,3,4])
y=np.array([1,2,3,4])
print("addition :",x+y)
print("subtraction :",x-y)
print("multiplication :",x*y)
print("division :",x/y)
print("division :",x//y)
print("Remender :",x%y)



addition : [2 4 6 8]
subtraction : [0 0 0 0]
multiplication : [ 1  4  9 16]
division : [1. 1. 1. 1.]
division : [1 1 1 1]
Remender : [0 0 0 0]
multiplication : 30


In [9]:
#multipling the two matrix
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(n)
print("multiplication :",m.dot(n))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
multiplication : [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
