Unary Operation 

In [16]:
import numpy as np
arr=np.array([[7,4,2],[9,5,1],[2,1,3]])
print(arr)
print("the largest element in array :",arr.max())
print("Row wise largest element :",arr.max(axis=1))
print("column wise largest element :",arr.max(axis=0))
print("the Minimum element in array :",arr.min())
print("Row wise Minimum element :",arr.min(axis=1))
print("column wise Minimum element :",arr.min(axis=0))
print("The sum of every element in array :",arr.sum())


# print("Total element in array :",arr.count()) #this will be throw an error. NO problem , solution is here
#Total element in array
print("Total element in array :",arr.size)

# print("Average of All elments :",arr.avg())  #this will be throw an error. NO problem , solution is here
print("Average of All elments :",np.average(arr))

[[7 4 2]
 [9 5 1]
 [2 1 3]]
the largest element in array : 9
Row wise largest element : [7 9 3]
column wise largest element : [9 5 3]
the Minimum element in array : 1
Row wise Minimum element : [2 1 1]
column wise Minimum element : [2 1 1]
The sum of every element in array : 34
Total element in array : 9
Average of All elments : 3.7777777777777777
